// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type DepartemenTableRow = {
    id: string;
    name: string;
    description: string;
  };

  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    password: string;
  };

  type ProjectTableRow = {
    id: string;
    name: string;
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
    };
    write: {
      email: string;
      password: string;
    };
    params: {};
    actions: {};
  };

  type AllDepartemenViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
    };
    write: {
      name: string;
      description: string;
    };
    params: {};
    actions: {};
  };

  type AllProjectViewRow = {
    read: {
      id: string;
      name: string;
    };
    write: {
      name: string;
    };
    params: {};
    actions: {};
  };

  interface ProjectSchema extends QoreSchema {
    allMember: AllMemberViewRow;
    allDepartemen: AllDepartemenViewRow;
    allProject: AllProjectViewRow;
  }
}
